// constants/images.ts - LOCAL VERSION (NO UNSPlASH DEPENDENCY)

export const MEDICAL_IMAGES = {
  // ============ HERO & BANNERS ============
  hero: {
    main: '/images/hero/doctor-patient.jpg',
    hospital: '/images/hero/hospital.jpg',
  },

  // ============ CATEGORY BANNERS ============
  categories: {
    mobility: '/images/categories/mobility.jpg',
    respiratory: '/images/categories/respiratory.jpg',
    hospitalFurniture: '/images/categories/hospital-furniture.jpg',
    diagnostic: '/images/categories/diagnostic.jpg',
    ppe: '/images/categories/ppe.jpg',
    homeCare: '/images/categories/home-care.jpg',
  },

  // ============ PRODUCT IMAGES - LOCAL PATHS ============
  products: {
    wheelchair: '/images/products/wheelchair.jpg',
    wheelchairElectric: '/images/products/wheelchair2.jpg',
    oxygen: '/images/products/oxygen.jpg',
    cpap: '/images/products/oxygen.jpg',
    hospitalBed: '/images/products/hospital-bed.jpg',
    examTable: '/images/products/medical-bed7.jpg',
    bpMonitor: '/images/products/bp-monitor.jpg',
    stethoscope: '/images/products/stethoscope.jpg',
    thermometer: '/images/products/thermometer.jpg',
    n95Mask: '/images/products/ppe-mask.jpg',
    gloves: '/images/products/gloves.jpg',
    patientMonitor: '/images/products/patient-monitor.jpg',
  },

  // ============ ABOUT & CONTACT ============
  about: {
    team: '/images/about/team.jpg',
    facility: '/images/about/facility.jpg',
  },
  contact: {
    office: '/images/contact/office.jpg',
  },
  testimonials: {
    doctor1: '/images/testimonials/doctor1.jpg',
    doctor2: '/images/testimonials/doctor2.jpg',
    patient1: '/images/testimonials/patient1.jpg',
    patient2: '/images/testimonials/patient2.jpg',
  },
};

// ============ PRODUCTS DATABASE WITH LOCAL IMAGES ============
export const PRODUCTS = [
  {
    id: 1,
    name: 'Premium Lightweight Wheelchair',
    slug: 'premium-lightweight-wheelchair',
    sku: 'MW-1001',
    price: 299.99,
    salePrice: 249.99,
    image: '/images/products/wheelchair.jpg',  // LOCAL PATH
    category: 'Mobility Aids',
    categorySlug: 'mobility-aids',
    brand: 'Goodwill Medical',
    rating: 4.8,
    reviewCount: 124,
    inventory: 15,
    description: 'Lightweight aluminum frame wheelchair with comfortable padded seat.',
    deliveryEstimate: '2-3 business days',
    warranty: '2 years',
  },
  {
    id: 2,
    name: 'Electric Power Wheelchair',
    slug: 'electric-power-wheelchair',
    sku: 'MW-1002',
    price: 1299.99,
    salePrice: 1099.99,
    image: '/images/products/wheelchair.jpg',  // LOCAL PATH
    category: 'Mobility Aids',
    categorySlug: 'mobility-aids',
    brand: 'Goodwill Medical',
    rating: 4.7,
    reviewCount: 56,
    inventory: 8,
    description: 'Electric wheelchair with joystick control and long battery life.',
    deliveryEstimate: '5-7 business days',
    warranty: '3 years',
  },
  {
    id: 3,
    name: 'Portable Oxygen Concentrator',
    slug: 'portable-oxygen-concentrator',
    sku: 'RE-2001',
    price: 899.99,
    salePrice: 799.99,
    image: '/images/products/oxygen.jpg',  // LOCAL PATH
    category: 'Respiratory Equipment',
    categorySlug: 'respiratory',
    brand: 'HealthCare Pro',
    rating: 4.9,
    reviewCount: 89,
    inventory: 12,
    description: 'Compact and lightweight oxygen concentrator. Battery lasts up to 5 hours.',
    deliveryEstimate: '2-3 business days',
    warranty: '2 years',
  },
  {
    id: 4,
    name: 'CPAP Machine',
    slug: 'cpap-machine',
    sku: 'RE-2002',
    price: 599.99,
    salePrice: 549.99,
    image: '/images/products/oxygen.jpg',  // LOCAL PATH
    category: 'Respiratory Equipment',
    categorySlug: 'respiratory',
    brand: 'MedTech',
    rating: 4.8,
    reviewCount: 142,
    inventory: 18,
    description: 'Auto-adjusting CPAP with heated humidifier.',
    deliveryEstimate: '2-3 business days',
    warranty: '2 years',
  },
  {
    id: 5,
    name: 'Adjustable Hospital Bed',
    slug: 'adjustable-hospital-bed',
    sku: 'HF-3001',
    price: 1299.99,
    image: '/images/products/hospital-bed.jpg',  // LOCAL PATH
    category: 'Hospital Furniture',
    categorySlug: 'hospital-furniture',
    brand: 'CarePlus',
    rating: 4.7,
    reviewCount: 56,
    inventory: 7,
    description: 'Fully adjustable electric bed with remote control.',
    deliveryEstimate: '7-10 business days',
    warranty: '5 years',
  },
  {
    id: 6,
    name: 'Digital Blood Pressure Monitor',
    slug: 'digital-bp-monitor',
    sku: 'DD-4001',
    price: 49.99,
    image: '/images/products/bp-monitor.jpg',  // LOCAL PATH
    category: 'Diagnostic Devices',
    categorySlug: 'diagnostic',
    brand: 'Vital Signs',
    rating: 4.8,
    reviewCount: 203,
    inventory: 45,
    description: 'Automatic inflation, large LCD display, detects irregular heartbeat.',
    deliveryEstimate: '1-2 business days',
    warranty: '1 year',
  },
  {
    id: 7,
    name: 'Professional Stethoscope',
    slug: 'professional-stethoscope',
    sku: 'DD-4002',
    price: 89.99,
    salePrice: 79.99,
    image: '/images/products/stethoscope.jpg',  // LOCAL PATH
    category: 'Diagnostic Devices',
    categorySlug: 'diagnostic',
    brand: 'MedTech',
    rating: 4.9,
    reviewCount: 178,
    inventory: 32,
    description: 'Dual-head stethoscope with non-chill rim.',
    deliveryEstimate: '1-2 business days',
    warranty: '2 years',
  },
  {
    id: 8,
    name: 'N95 Respirator Masks (50 pack)',
    slug: 'n95-masks-50-pack',
    sku: 'PPE-5001',
    price: 89.99,
    image: '/images/products/ppe-mask.jpg',  // LOCAL PATH
    category: 'PPE & Disposables',
    categorySlug: 'ppe',
    brand: 'HealthCare Pro',
    rating: 4.7,
    reviewCount: 167,
    inventory: 0,
    description: 'FDA-approved N95 respirator masks. 95% filtration efficiency.',
    deliveryEstimate: '3-5 business days',
    warranty: 'Non-returnable',
  },
  {
    id: 9,
    name: 'Nitrile Exam Gloves (100 pack)',
    slug: 'nitrile-gloves-100-pack',
    sku: 'PPE-5002',
    price: 24.99,
    image: '/images/products/gloves.jpg',  // LOCAL PATH
    category: 'PPE & Disposables',
    categorySlug: 'ppe',
    brand: 'Goodwill Medical',
    rating: 4.6,
    reviewCount: 98,
    inventory: 150,
    description: 'Powder-free nitrile gloves. Latex-free, puncture resistant.',
    deliveryEstimate: '1-2 business days',
    warranty: '30-day return',
  },
  {
    id: 10,
    name: 'Patient Monitor',
    slug: 'patient-monitor',
    sku: 'HC-6001',
    price: 2499.99,
    image: '/images/products/patient-monitor.jpg',  // LOCAL PATH
    category: 'Home Care Supplies',
    categorySlug: 'home-care',
    brand: 'Vital Signs',
    rating: 4.9,
    reviewCount: 34,
    inventory: 5,
    description: 'Monitors ECG, SpO2, blood pressure, and temperature.',
    deliveryEstimate: '3-5 business days',
    warranty: '3 years',
  },
];

export const CATEGORIES = [
  {
    id: 1,
    name: 'Mobility Aids',
    slug: 'mobility-aids',
    image: '/images/categories/mobility.jpg',
    description: 'Wheelchairs, walkers, scooters',
    icon: '🦽',
  },
  {
    id: 2,
    name: 'Respiratory',
    slug: 'respiratory',
    image: '/images/categories/respiratory.jpg',
    description: 'Oxygen, CPAP, ventilators',
    icon: '💨',
  },
  {
    id: 3,
    name: 'Hospital Furniture',
    slug: 'hospital-furniture',
    image: '/images/categories/hospital-furniture.jpg',
    description: 'Beds, tables, chairs',
    icon: '🛏️',
  },
  {
    id: 4,
    name: 'Diagnostic',
    slug: 'diagnostic',
    image: '/images/categories/diagnostic.jpg',
    description: 'BP monitors, stethoscopes',
    icon: '🩺',
  },
  {
    id: 5,
    name: 'PPE',
    slug: 'ppe',
    image: '/images/categories/ppe.jpg',
    description: 'Masks, gloves, gowns',
    icon: '🧤',
  },
  {
    id: 6,
    name: 'Home Care',
    slug: 'home-care',
    image: '/images/categories/home-care.jpg',
    description: 'Daily living aids',
    icon: '🏠',
  },
];
